<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $viewModel \Hokodo\BNPL\ViewModel\Checkout\OnepageSuccess
 * @var \Magento\Framework\Escaper $escaper
 */

$viewModel = $block->getData('viewModel');
?>
<script>
    require(['Hokodo_BNPL/js/segment/core'], function(segment) {
        segment.trackOrderPlaced(
            '<?= $viewModel->getSelectedPaymentMethodCode() ?>',
            '<?= $viewModel->getOrder()->getIncrementId() ?>',
            '<?= (float) ($viewModel->getOrder()->getGrandTotal() - $viewModel->getOrder()->getShippingAmount()) ?>',
            '<?= $viewModel->getOrder()->getOrderCurrencyCode() ?>'
        );
    })
</script>
