<?php
/**
 * Copyright © 2018-2023 Hokodo. All Rights Reserved.
 * See LICENSE for license details.
 */

/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $viewModel \Hokodo\BNPL\ViewModel\Checkout\OnepageSuccess
 */

$viewModel = $block->getData('viewModel');
?>
<?php if ($viewModel->canPushAnalytics()): ?>
<script>
    require(['Hokodo_BNPL/js/segment/core'], function(segment) {
        segment.trackOrderPlaced(
            '<?= $viewModel->getSelectedPaymentMethodCode(); ?>',
            '<?= $viewModel->getOrder()->getIncrementId(); ?>',
            '<?= number_format(
                (float) ($viewModel->getOrder()->getGrandTotal() - $viewModel->getOrder()->getShippingAmount()),
                2
             ); ?>',
            '<?= $viewModel->getOrder()->getOrderCurrencyCode(); ?>',
            '<?= $viewModel->getQuoteId(); ?>'
        );
    })
</script>
<?php endif; ?>
