<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $viewModel \Hokodo\BNPL\ViewModel\Checkout\OnepageSuccess
 */

$viewModel = $block->getData('viewModel');
?>
<script>
    require(['Hokodo_BNPL/js/segment/core'], function(segment) {
        segment.trackOrderPlaced(
            '<?= $viewModel->getSelectedPaymentMethodCode() ?>',
            '<?= $viewModel->getOrder()->getIncrementId() ?>'
        );
    })
</script>
