repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: trailing-whitespace
      - id: check-xml
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
        args: ["--indent=4", "--autofix", "--no-sort-keys"]
  - repo: https://github.com/digitalpulp/pre-commit-php.git
    rev: 1.4.0
    hooks:
      - id: php-cs-fixer
        files: \.(php)$
