<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $viewModel \Hokodo\BNPL\ViewModel\Checkout\OnepageSuccess
 */

$viewModel = $block->getData('viewModel');
?>
<?php if ($viewModel->isEnable()): ?>
	<div class="hokodo-checkout">
	    <?= $viewModel->getLabelBtn(); ?>
		<img
			src="<?php echo $this->getViewFileUrl('Hokodo_BNPL/img/hokodo_btn_background.svg'); ?>"
			alt="Hokodo"
		/>
	</div>
<?php endif ?>
