<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $viewModel \Hokodo\BNPL\ViewModel\ProductButton
 */

$viewModel = $block->getData('viewModel');
?>
<?php if ($viewModel->isEnable()): ?>
	<?php $apiKey = $viewModel->getApiKey() ?>
	<div class="btn hokodo-checkout">
	    <?= $viewModel->getLabelBtn(); ?>
		<img
			src="<?php echo $this->getViewFileUrl('Hokodo_BNPL/img/hokodo_btn_background.svg'); ?>"
			alt="Hokodo"
		/>
	</div>
	<?php if ($apiKey): ?>
		<?php $sdkPublicToken = 'pk_test_'.$apiKey ?>
		<?php if ($viewModel->isSandbox()): ?>
			<script src="https://js-sandbox.hokodo.co/hokodo-js/v1"></script>
		<?php else: ?>
			<script src="https://js.hokodo.co/hokodo-js/v1"></script>
		<?php endif ?>
		<script type="text/javascript">
			const hokodo = Hokodo('<?= $sdkPublicToken ?>'); 
		    hokodo.marketing();
		</script>
		<div style="display: none;" class="hokodo-lightbox" data-bind="mageInit: {
        'Magento_Ui/js/modal/modal':{
            'type': 'popup',
            'modalClass': 'modal-hokodo-lightbox',
            'trigger': '.btn.hokodo-checkout',
            'buttons': false
        }}">
        	<hokodo-marketing data-element="lightbox"></hokodo-marketing>
    	</div>
	<?php endif ?>
<?php endif ?>
