<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $viewModel \Hokodo\BNPL\ViewModel\Marketing\CreditLimitBanners
 */
$viewModel = $block->getData('viewModel');
$viewModel->setBannerConfig($block->getData('bannerConfig') ?? []);
?>

<?php if ($viewModel->isEnabled()): ?>
    <div class="hokodo-marketing-banner-wrapper <?= $block->getData('extraClasses') ?? '' ?>"
         data-bind="scope:'<?= $block->getNameInLayout() ?>'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "<?= $block->getNameInLayout() ?>": {
                            "component": "Hokodo_BNPL/js/sdk/marketing/banner",
                            "config": <?= $viewModel->getJsConfig() ?>
                        }
                    }
                }
            }
        }
    </script>
<?php endif; ?>
