<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $viewModel \Hokodo\BNPL\ViewModel\Marketing\CreditLimitBanners
 */
$viewModel = $block->getData('viewModel');
?>

<?php if ($viewModel->isEnabled()): ?>
<div data-bind="scope:'hokodo-product-credit-limit-banner' ">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "hokodo-product-credit-limit-banner": {
                        "component": "Hokodo_BNPL/js/sdk/marketing/product-banner"
                    }
                }
            }
        }
    }
</script>
<?php endif; ?>
