<hokodo-marketing data-element="credit-limit-banner"></hokodo-marketing>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "hokodo-product-credit-limit-banner": {
                        "component": "Hokodo_BNPL/js/sdk/marketing/product-banner"
                    }
                }
            }
        }
    }
</script>
