<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $viewModel \Hokodo\BNPL\ViewModel\SdkLoader
 */

$viewModel = $block->getData('viewModel');
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Hokodo_BNPL/js/sdk/core":{
                "url":"<?= $viewModel->getSdkUrl() ?>",
                "key":"<?= $viewModel->getSdkKey() ?>",
                "faq":"<?= $viewModel->getMarketingFaqUrl() ?>"
            }
        }
    }
</script>
