<?php

declare(strict_types=1);
/** @var $block Hokodo\BNPL\Block\System\Config\Form\Field\PaymentLog\ViewLog */
?>

<div class="actions actions-viewlog">
    <a href="<?= $block->getPageUrl() ?>" title="<?php echo $block->escapeHtml($block->getButtonLabel()) ?>" class="action test-connection action-primary">
        <span><?php echo $block->escapeHtml($block->getButtonLabel()) ?></span>
    </a>
</div>
