<?php
/**
 * Copyright © 2018-2023 Hokodo. All Rights Reserved.
 * See LICENSE for license details.
 */

/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $viewModel \Hokodo\BNPL\ViewModel\SdkLoader
 */

$viewModel = $block->getData('viewModel');

if ($viewModel->isModuleActive()):
    ?>

    <script type="text/x-magento-init">
    {
        "*": {
            "Hokodo_BNPL/js/sdk/core": <?= $viewModel->getJsConfig() ?>
        }
    }
    </script>
<?php endif; ?>
